controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_route:
    path: '/{any}'
    controller: App\Controller\homeController::renderHome
    requirements:
        any: '.+'